const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
process.chdir(path.resolve(__dirname,'..'));
const html=fs.readFileSync('index.html','utf8'), src=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const elements=new Map(),exportButtons=Array.from({length:5},()=>({disabled:true}));
const document={getElementById:id=>{if(!elements.has(id))elements.set(id,{value:'',textContent:'',disabled:false});return elements.get(id)},querySelectorAll:()=>exportButtons};
const ctx={location:{protocol:'file:',hostname:''},document};vm.createContext(ctx);vm.runInContext(src,ctx);
const input='Silver stars shine.\nSILVER   STARS SHINE!\nTwo words\nSolitary\n\n!!!\nAmber angels ascend\nDON’T STOP\nCafé circles carry\n';
const r=ctx.processReview(input,'test');
assert.equal(r.clean.join('\n'),'AMBER ANGELS ASCEND\nSILVER STARS SHINE');assert.equal(r.inputLines,9);assert.equal(r.held.length,7);assert.equal(r.duplicates.length,1);assert.equal(r.counts.TWO_WORDS,2);assert.equal(r.original,input);
assert.equal(ctx.processReview('Alpha beta gamma\rAlpha beta gamma\r','test').duplicates.length,1);
assert.equal(ctx.processReview('Alpha beta gamma\nALPHA-BETA-GAMMA','test').duplicates.length,1);
assert.equal(ctx.processReview('<img onerror=alert(1)>','test').held[0].reason,'CODE_LIKE');
assert.equal(ctx.processReview('Broken \uFFFD letters here','test').held[0].reason,'CHARACTERS_NEED_REVIEW');
assert.equal(ctx.processReview('','test').inputLines,0);
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);assert.equal(new Set(ids).size,ids.length);
for(const m of html.matchAll(/onclick="([a-zA-Z]+)\(/g))assert.equal(typeof ctx[m[1]],'function',m[1]);
const manifest=JSON.parse(fs.readFileSync('manifest.json'));for(const i of manifest.icons)assert.ok(fs.existsSync(i.src));
document.getElementById('reviewInput').value=input;ctx.sortReview();assert.ok(exportButtons.every(x=>!x.disabled));
assert.equal(document.getElementById('reviewInput').value,input);
const downloads=[];ctx.downloadText=(name,text)=>downloads.push({name,text});
for(const kind of ['clean','review','duplicates','original','log'])ctx.exportReview(kind);
assert.equal(downloads.length,5);assert.equal(downloads[0].text,r.clean.join('\n'));assert.match(downloads[1].text,/LINE 3 \| TWO_WORDS \| Two words/);assert.match(downloads[2].text,/SILVER   STARS SHINE!/);assert.equal(downloads[3].text,input);assert.equal(JSON.parse(downloads[4].text).accountingPassed,true);
ctx.invalidateReview();assert.ok(exportButtons.every(x=>x.disabled));ctx.exportReview('clean');assert.equal(downloads.length,5);
const lines=Array.from({length:1100},(_,i)=>'ALPHA BETA '+String.fromCharCode(65+Math.floor(i/676),65+Math.floor(i/26)%26,65+i%26));
const large=ctx.processReview(lines.concat(lines).join('\n'),'scale');assert.equal(large.clean.length,1100);assert.equal(large.duplicates.length,1100);assert.equal(large.inputLines,2200);
console.log('PASS: core sorting, 3-word rule, code/encoding review, punctuation deduplication, preservation/accounting, 2200-line batch, download payloads, stale export guards, unique IDs, active handler definitions and icon presence. Browser clicks and installation are not covered by this test.');
